### ISSUE TITLE
Bar location incorrect when chat is collapsed

### ISSUE THREAD

**Issue by guillaume009** [SirHitech/MapleXPBar#11]
When the chat is collapsed, the bar is on top of the text. Would be nice if it was a bit higher

![image](https://github.com/SirHitech/MapleXPBar/assets/8568544/6f9190eb-a433-46ff-98ca-1a585844c707)

**Comment by SirHitech** [comment]
Okay interesting, thanks for pointing this out - this occurs when "Transparent chatbox" is checked in the Resizable category of the Interfaces panel in Settings. As a temporary workaround, you can uncheck this box if the bar is more important than the transparency, but I will work on a fix for this!

![image](https://github.com/SirHitech/MapleXPBar/assets/16417862/668fe0fa-3822-46b6-8357-ddaaf179c34c)

![image](https://github.com/SirHitech/MapleXPBar/assets/16417862/fffa1099-400f-458c-8b7f-d4e6c2b46d7b)

**Comment by guillaume009** [comment]
Thank you for the workaround. Will use that in the meantime!

**Comment by SirHitech** [comment]
The issue has been fixed and is live on the runelite client. Thanks for reporting, apologies for taking a while to around to it!
