### ISSUE TITLE
[Feature Request] Add option to ignore hitpoints skill

### ISSUE THREAD

**Issue by Anderzenn** [SirHitech/MapleXPBar#16]
As the title states, I would love for an option to have the xp bar ignore the hitpoints skill when you have the "Show Most Recent Skill" option enabled.

When you're training melee it ends up taking over the xp bar, so having an option to ignore it would be a nice little "QoL" feature IMO.

**Comment by SirHitech** [comment]
Thank you very much for the suggestion! I have made the change on my end and [opened a request](https://github.com/runelite/plugin-hub/pull/6860) to update the plugin on Runelite. Once it's approved it may take a few days or so to release and be available on the client.

Enjoy, and thank you for using my plugin!

**Comment by Anderzenn** [comment]
> Thank you very much for the suggestion! I have made the change on my end and [opened a request](https://github.com/runelite/plugin-hub/pull/6860) to update the plugin on Runelite. Once it's approved it may take a few days or so to release and be available on the client.
> 
> Enjoy, and thank you for using my plugin!

Awesome! Thank you for the quick addition! I can confirm it is working as I expected :)
