### ISSUE TITLE
Don't show maxed skills' bars

### ISSUE THREAD

**Issue by hawkins** [SirHitech/MapleXPBar#6]
Hey, I noticed that when I attack something with melee, it shows me the Hitpoints skill progress bar instead of Attack. However, my Hitpoints skill is maxed and my Attack skill is not, so I'm more interested in seeing the Attack skill's xp bar. I'm thinking I would like a config setting to not show the xp bar for level 99+ skills, so that multi-skill actions like combat or barbarian fishing show the most relevant xp bar.

Not sure how best to do this. It looks like a change to `MapleXPBarPlugin#onStatChanged`, maybe changing the condition to also check if the skill is already level 99 before setting `currentSkill`? But that raises the question, should this be locked behind a config option, and should that option be customizable with its cap? I.e., would one person want to see bars until 200,000,000 xp or just level 126/99 etc. I'm happy to PR this but not sure the best approach for flexibility.

**Comment by SirHitech** [comment]
Yup, something the original creator of the recent xp feature [mentioned](https://github.com/SirHitech/MapleXPBar/pull/2#issue-1174430215) as well.

I think there's three ways of solving this:
- Your solution - one checkbox for hiding skills if they hit a certain threshold, and one dropdown for what the threshold is (lvl99, 200m xp, etc.) Very clean and simple solution.
- A checkbox for every hybrid action in the game (ignore hitpoints xp in combat; ignore strength xp when barb fishing, etc.) Don't absolutely love this idea, but would give people the most flexibility maybe? Would require knowledge of all the various use cases, and I haven't played the game in quite some time. If there's too many scenarios this solution becomes much less appealing.
- Have a config option of every skill to be ignored. I don't know of a good way to do this without putting 23 different config options out there, which is _okay_ but cluttery.

**Comment by hawkins** [comment]
Good shout, appreciate the other ideas! 

Personally I think option 2 isn't worth the trouble, because it'll mean added maintenance load to update that list every so often. Option 3 doesn't seem too bad because we could put them in a new configuration section which could auto collapse to hide the clutter. So, could look like 23 checkboxes for `showX`, then reference those varaibles in the `onStatChanged` method. Ultimately I think either option 1 or 3 would be easy enough to both maintain and understand as a user

Example of a collapsible config section (from 117 HD's config): 
![image](https://github.com/SirHitech/MapleXPBar/assets/9123458/e882067f-2c8e-4940-a87d-ce9d15398c87)

**Comment by SirHitech** [comment]
Okay nice, with that I'd be totally onboard for 1 and/or 3, since I suppose both is also an option. I may not have much free time in the next coming weeks so if you'd like to tackle this then go ahead, otherwise I'll get to it eventually

**Comment by hawkins** [comment]
Sounds good, I'll probably send a PR in sometime in the next week or so then! Appreciate it
