### ISSUE TITLE
Chat box

### ISSUE THREAD

**Issue by AlfrescoRS** [SirHitech/MapleXPBar#8]
Hi, I love this plugin, I use it all the time.
I use it with customizable XP drops plugin to remove the in-game xp bar so that this is my main one.

The only thing I can think of to make it better is for the Maple XP Bar to still show up when the Chat Box is hidden.
A toggle option for it would be nice :)

Thanks,
Alfresco

**Comment by SirHitech** [comment]
Thanks for the feedback, and I'm so happy to hear that you enjoy my plugin! I'll take a look at adding that

**Comment by SirHitech** [comment]
Change will go live when the [PluginHub pull request](https://github.com/runelite/plugin-hub/pull/4665) is merged in
